name: CD / Publish release
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Display build environment
        run: printenv
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version in readme
        uses: weareyipyip/set-version-action@v2
        with:
          source: tag
          file_path: README.md
      - name: Set version in mix.exs
        uses: weareyipyip/set-version-action@v2
        with:
          source: tag
          file_path: mix.exs

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.x
          elixir-version: 1.12.x
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get

      - name: Compile code
        run: mix compile
      - name: Create docs
        run: mix docs
      - name: Publish release
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
